language: julia

os:
  - linux

branches:
  only:
    - master
  
julia:
  - 1.3
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); Pkg.add("Coverage");'
  - julia -e 'import LocalCongruence; cd(dirname(dirname(pathof(LocalCongruence)))); include(joinpath("docs", "make.jl"))'
  - julia -e 'using Coverage; import LocalCongruence; cd(dirname(dirname(pathof(LocalCongruence)))); Codecov.submit(process_folder())'

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/build
  on:
    branch: master
